name: tutorial1
on: push
jobs:
  job1:
       name: job1
       runs-on: ubuntu-latest
       steps:
       - name: step1
         run: |
            echo "hello fromjob1"
            echo "Today's Date is $(date)"

  job2:
       name: job2
       runs-on: windows-latest
       steps:
       - name: step2
         run: | 
            echo "hello from job2"
            echo "Today's date is $(date)"

  job3:
       name: job3
       runs-on: ubuntu-latest
       steps:
       - name: step3
         run: |
           echo "hello from job3"
           echo "Today's date is $(date)"

         
  job4:
       name: job4
       needs: [job1, job2]
       runs-on: ubuntu-latest
       steps:
       - name: step4
         run: |
          echo "I am job4"
          echo "Todays date is $(date)"
